#!groovy

node {
    stage('Checkout'){
        checkout scm
    }

    stage('Build') {
        echo "My branch is: ${env.BRANCH_NAME}"
        def flavor = flavor(env.BRANCH_NAME)
        echo "Building flavor ${flavor}"
        sh "./gradlew clean build"
    }

}